### ISSUE TITLE
Judging submission

### ISSUE THREAD

**Issue by tmcclell** [greenscale-nandesh/if-unofficial-models#6]
## Tasks

- [x] Screengrab of plugin running @rossf7 
- [x] Video @tmcclell 
- [ ] Updating hack issue https://github.com/Green-Software-Foundation/hack/issues/54 @greenscale-nandesh 
- [ ] Submit form on hack site 

Create a <3 minute video to submit the project for judging per https://github.com/Green-Software-Foundation/hack/wiki/Submit-your-project-for-judging.

**Comment by tmcclell** [comment]
![Screenshot 2024-04-02 123843](https://github.com/greenscale-nandesh/if-unofficial-models/assets/53481728/8989e762-1789-4121-b69d-9237e56261fe)

**Comment by SFulpius** [comment]
For the video it would be good if we have some interesting data to show.
@rossf7 you mentioned some stress test for falco. I think it would be interesting to compute SCI while they are running. Do stress tests run automatically or do we need to run them manually?

**Comment by rossf7** [comment]
Hi @tmcclell @greenscale-nandesh @SFulpius, 
here is the screen capture I've uploaded it to my G Drive. 
https://drive.google.com/file/d/1Jx0Q6dagggUexr6y2vWpg5yH3O-V-vm9/view?usp=drive_link

It's 2:13 so could we add an intro and include the team photo? 

> you mentioned some stress test for falco. I think it would be interesting to compute SCI while they are running. Do stress tests run automatically or do we need to run them manually?

@SFulpius The stress test is always running and is a combination of the microservices-demo and stress-ng.  I mentioned that in the screencast. https://github.com/GoogleCloudPlatform/microservices-demo

This is the 1st iteration of the platform while we prototype. We plan to create the cluster nodes on demand trigged by a GitHub Actions workflow.

**Comment by tmcclell** [comment]
@rossf7 - Your screen capture is fabulous! Don't think we need to do anything more. We can also add the team pic in the release notes or just reference the team in it. Thought?

**Comment by rossf7** [comment]
@tmcclell Thank you! 

I took another look at the submission docs and there is this presentation template.
https://docs.google.com/presentation/d/1HNXp3rDkmP2ZTkdEjG3DIPb0O_SNgiGaCbPcIbrGFbk/edit?usp=sharing

I'll fill that in tomorrow and record another ~30 secs and combine it with the demo.  With that we should be good to go!

**Comment by rossf7** [comment]
I've uploaded the new video. It was a few slides as intro before the demo. Its 2:48 so just under 😅 

https://www.youtube.com/watch?v=sn0zrhghrjE

Edit: Slides link https://docs.google.com/presentation/d/1xXVTVBOXM1ZJXWYE67anPl9cWEwAis8-KZoJL4p-UM8/edit?usp=sharing

**Comment by tmcclell** [comment]
[heart]         Tammy McClellan reacted to your message:
________________________________
